### PR TITLE
Change severity level

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
I suggest this change, as then any suggestions from vale show up in the problems view, instead of as hints, which are kind of hard to see and find in the editor.

### CODE REVIEW

**Comment by lunaryorn** [comment]
Thanks 😊 

I must admit, tho, that I can't really imagine how this change looks like; could you perhaps show a screenshot to illustrate the difference?

**Comment by ChrisChinchilla** [comment]
Sure, here you go.

screenshot 2018-08-11 16 56 30
screenshot 2018-08-11 16 55 59
screenshot 2018-08-11 16 54 40

I think that makes it clear :)

**Comment by lunaryorn** [comment]
Understood!  Thanks for he screenshots.

I merged the PR, but I don’t have time to cut a release until Tuesday evening.  I hope that’s ok?

**Comment by lunaryorn** [comment]
PS:  thanks for your contribution ❤️

**Comment by ChrisChinchilla** [comment]
@lunaryorn No worries, thanks!

**Comment by lunaryorn** [comment]
@ChrisChinchilla Update's out!

**Pull request merged**
